# Generated by Django 5.0.3 on 2024-04-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
